import './stack.css'
import React, { useState } from 'react'
import { Col, Container, Row } from 'react-bootstrap'
import WreckingBall from '../components/wrecking-ball'

export const Stack = () => {
  const [logoList, setLogoList] = useState<string[]>([
    '/logos/Advanced Solutions Lab.png',
    '/logos/AI Hub.png',
    '/logos/AI Platform Data Labeling Service.png',
    '/logos/AI Platform.png',
    '/logos/API Analytics.png',
    '/logos/API Monetization.png',
    '/logos/Apigee API Platform.png',
    '/logos/Apigee Sense.png',
    '/logos/App Engine.png',
    '/logos/AutoML Natural Language.png',
    '/logos/AutoML Tables.png',
    '/logos/AutoML Translation.png',
    '/logos/AutoML Video Intelligence.png',
    '/logos/AutoML Vision.png',
    '/logos/BigQuery.png',
    '/logos/Cloud APIs.png',
    '/logos/Cloud Armor.png',
    '/logos/Cloud AutoML.png',
    '/logos/Cloud Bigtable.png',
    '/logos/Cloud Billing API.png',
    '/logos/Cloud Build.png',
    '/logos/Cloud CDN.png',
    '/logos/Cloud Code for IntelliJ.png',
    '/logos/Cloud Code.png',
    '/logos/Cloud Composer.png',
    '/logos/Cloud Console.png',
    '/logos/Cloud Data Catalog.png',
    '/logos/Cloud Data Fusion.png',
    '/logos/Cloud Dataflow.png',
    '/logos/Cloud Datalab.png',
    '/logos/Cloud Dataprep.png',
    '/logos/Cloud Dataproc.png',
    '/logos/Cloud Datastore.png',
    '/logos/Cloud Deployment Manager.png',
    '/logos/Cloud DNS.png',
    '/logos/Cloud Endpoints.png',
    '/logos/Cloud External IP Addresses.png',
    '/logos/Cloud Filestore.png',
    '/logos/Cloud Firestore.png',
    '/logos/Cloud Firewall Rules.png',
    '/logos/Cloud Functions.png',
    '/logos/Cloud IAM.png',
    '/logos/Cloud Inference API.png',
    '/logos/Cloud IoT Core.png',
    '/logos/Cloud Jobs API.png',
    '/logos/Cloud Load Balancing.png',
    '/logos/Cloud Memorystore.png',
    '/logos/Cloud Mobile App.png',
    '/logos/Cloud NAT.png',
    '/logos/Cloud Natural Language API.png',
    '/logos/Cloud Network.png',
    '/logos/Cloud PubSub.png',
    '/logos/Cloud Resource Manager.png',
    '/logos/Cloud Router.png',
    '/logos/Cloud Routes.png',
    '/logos/Cloud Run.png',
    '/logos/Cloud Scheduler.png',
    '/logos/Cloud SDK.png',
    '/logos/Cloud Security Command Center.png',
    '/logos/Cloud Security Scanner.png',
    '/logos/Cloud Service Mesh.png',
    '/logos/Cloud Shell.png',
    '/logos/Cloud Source Repositories.png',
    '/logos/Cloud Spanner.png',
    '/logos/Cloud Speech-to-Text.png',
    '/logos/Cloud SQL.png',
    '/logos/Cloud Storage.png',
    '/logos/Cloud Tasks.png',
    '/logos/Cloud Test Lab.png',
    '/logos/Cloud Text-to-Speech.png',
    '/logos/Cloud Tools for Eclipse.png',
    '/logos/Cloud Tools for PowerShell.png',
    '/logos/Cloud Tools for Visual Studio.png',
    '/logos/Cloud TPU.png',
    '/logos/Cloud Translation API.png',
    '/logos/Cloud Video Intelligence API.png',
    '/logos/Cloud Vision API.png',
    '/logos/Cloud VPN.png',
    '/logos/Compute Engine.png',
    '/logos/Container Registry.png',
    '/logos/Container-Optimized OS.png',
    '/logos/Debugger.png',
    '/logos/Dedicated Interconnect.png',
    '/logos/Developer Portal.png',
    '/logos/Dialog Flow Enterprise Edition.png',
    '/logos/Error Reporting.png',
    '/logos/Genomics.png',
    '/logos/GKE On-Prem.png',
    '/logos/GPU.png',
    '/logos/Gradle App Engine Plugin.png',
    '/logos/IDE Plugins.png',
    '/logos/javascript.png',
    '/logos/Key Management Service.png',
    '/logos/Kubernetes Engine.png',
    '/logos/Logging.png',
    '/logos/Maven App Engine Plugin.png',
    '/logos/Monitoring.png',
    '/logos/Partner Interconnect.png',
    '/logos/Persistent Disk.png',
    '/logos/Premium Network Tier.png',
    '/logos/Profiler.png',
    '/logos/react.png',
    '/logos/Recommendations AI.png',
    '/logos/SFMC.png',
    '/logos/Stackdriver.png',
    '/logos/Standard Network Tier.png',
    '/logos/svg-to-png-template.ai',
    '/logos/Trace.png',
    '/logos/Traffic Director.png',
    '/logos/Transfer Appliance.png',
    '/logos/typescript.png',
    '/logos/Virtual Private Cloud.png'
  ])
  return (
    <Container fluid className={'page'}>
      <Row>
        <h6>While I'm working on this page please enjoy this html canvas</h6>
      </Row>
      <Row>
        <Col lg={12}>
          <WreckingBall logos={logoList}/>
        </Col>
      </Row>
    </Container>
  )
}
