# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm i
    - run: npm build
    - name: Push directory to another repos
      uses: vinayb21/github-action-push-to-another-repo@1.4.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'build'
        destination-github-username: 'noahbjohnson'
        destination-repository-name: 'noahbjohnson.github.io'
        user-email: 'noah@noahbjohnson.net'


